import type { Metadata } from "next";
import "../globals.css";
import Header from "@/components/common/Header";
import Navbar from "@/components/common/Navbar";
import Footer from "@/components/common/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  params,
  children,
}: {
  children: React.ReactNode;
  params: { lang: string };
}) {
  const { lang } = await params;
  return (
    <html lang="en">
      <body>
        <Header lang={lang} />
        <Navbar lang={lang} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
